"""Observability hook that records the agent's tool-call activity.

A small demonstrator of Strands' typed hook system. The hook times every tool
the model invokes during a run and logs a one-line tool summary plus a token /
latency line per invocation, which makes the cheap local model's tool routing
and cost visible without touching any tool or domain logic. The pure formatting
is kept separate from the timing and logging side effects so it can be tested
directly.
"""

import logging
import time
from dataclasses import dataclass
from typing import TYPE_CHECKING

from strands.hooks import (
    AfterInvocationEvent,
    AfterToolCallEvent,
    BeforeToolCallEvent,
    HookRegistry,
)

if TYPE_CHECKING:
    from collections.abc import Callable, Sequence


@dataclass(frozen=True)
class ToolCall:
    """A single completed tool invocation observed during a run.

    Attributes:
        name: The tool's registered name.
        duration_ms: Wall-clock time the tool took, in milliseconds.
        succeeded: Whether the tool returned a successful result.
    """

    name: str
    duration_ms: float
    succeeded: bool


@dataclass(frozen=True)
class _ToolGroup:
    """Accumulated call count and total duration for one tool name."""

    count: int
    duration_ms: float


def _call_succeeded(status: str, exception: Exception | None) -> bool:
    """Return whether a finished tool call counts as successful.

    Args:
        status: The ``ToolResult`` status reported by the executor.
        exception: An exception raised by the tool, or None when it returned.

    Returns:
        True only when no exception was raised and the status is ``"success"``.
    """
    return exception is None and status == "success"


def summarize_tool_calls(calls: Sequence[ToolCall]) -> str:
    """Render one run's tool calls into a single readable line.

    Tools are grouped by name in first-seen order, each with its call count and
    summed duration, preceded by the totals and the number of failures.

    Args:
        calls: The tool calls recorded for a single agent invocation.

    Returns:
        A human-readable summary, or ``"no tool calls"`` when none were made.
    """
    if not calls:
        return "no tool calls"
    total_ms = sum(call.duration_ms for call in calls)
    failed = sum(1 for call in calls if not call.succeeded)
    grouped: dict[str, _ToolGroup] = {}
    for call in calls:
        previous = grouped.get(call.name)
        if previous is None:
            grouped[call.name] = _ToolGroup(count=1, duration_ms=call.duration_ms)
        else:
            grouped[call.name] = _ToolGroup(
                count=previous.count + 1,
                duration_ms=previous.duration_ms + call.duration_ms,
            )
    noun = "call" if len(calls) == 1 else "calls"
    header = f"{len(calls)} tool {noun}, {total_ms:.1f} ms total, {failed} failed"
    parts = ", ".join(
        f"{name} x{group.count} ({group.duration_ms:.1f} ms)" for name, group in grouped.items()
    )
    return f"{header}: {parts}"


def summarize_usage(
    *,
    input_tokens: int,
    output_tokens: int,
    total_tokens: int,
    model_latency_ms: int,
) -> str:
    """Render a run's token usage and model latency as one readable line.

    Args:
        input_tokens: Prompt tokens sent to the model across the run.
        output_tokens: Tokens generated by the model across the run.
        total_tokens: Combined token count for the run.
        model_latency_ms: Total model (inference) latency in milliseconds.

    Returns:
        A compact, human-readable usage summary.
    """
    return (
        f"tokens in={input_tokens} out={output_tokens} total={total_tokens}, "
        f"model latency {model_latency_ms} ms"
    )


class ToolCallObserver:
    """Strands hook provider that times and logs the model's tool calls.

    One instance tracks a single agent. It snapshots and resets at the end of
    each invocation, so :attr:`calls` and the logged summaries describe the most
    recent completed run only. Attach it via ``Agent(hooks=[ToolCallObserver()])``;
    keep a reference to a shared instance to read :attr:`calls` after a run (for
    benchmarking or a UI). Structurally satisfies the ``HookProvider`` protocol.
    """

    def __init__(
        self,
        *,
        clock: Callable[[], float] = time.perf_counter,
        logger: logging.Logger | None = None,
    ) -> None:
        """Initialise the observer.

        Args:
            clock: Monotonic clock used to time tool calls. Injectable so timing
                is deterministic under test.
            logger: Logger for the per-run summaries. Defaults to this module's
                logger.
        """
        self._clock = clock
        self._logger = logger if logger is not None else logging.getLogger(__name__)
        self._starts: dict[str, float] = {}
        self._calls: list[ToolCall] = []
        self._last_run: tuple[ToolCall, ...] = ()

    @property
    def calls(self) -> tuple[ToolCall, ...]:
        """The tool calls recorded for the most recent completed invocation."""
        return self._last_run

    def register_hooks(self, registry: HookRegistry, **_kwargs: object) -> None:
        """Subscribe to the tool-call and invocation lifecycle events.

        Args:
            registry: The agent's hook registry to register callbacks with.
            **_kwargs: Unused; present for forward compatibility with the
                ``HookProvider`` protocol.
        """
        registry.add_callback(BeforeToolCallEvent, self._on_tool_start)
        registry.add_callback(AfterToolCallEvent, self._on_tool_end)
        registry.add_callback(AfterInvocationEvent, self._on_invocation_end)

    def _on_tool_start(self, event: BeforeToolCallEvent) -> None:
        """Record the start time of a tool call, keyed by its use id."""
        self._starts[event.tool_use["toolUseId"]] = self._clock()

    def _on_tool_end(self, event: AfterToolCallEvent) -> None:
        """Record a finished tool call's duration and outcome."""
        start = self._starts.pop(event.tool_use["toolUseId"], None)
        duration_ms = 0.0 if start is None else (self._clock() - start) * 1000.0
        call = ToolCall(
            name=event.tool_use["name"],
            duration_ms=duration_ms,
            succeeded=_call_succeeded(event.result["status"], event.exception),
        )
        self._calls.append(call)
        self._logger.debug(
            "tool=%s succeeded=%s duration_ms=%.1f", call.name, call.succeeded, call.duration_ms
        )

    def _on_invocation_end(self, event: AfterInvocationEvent) -> None:
        """Snapshot the run, then log the tool-call summary and token metrics."""
        self._last_run = tuple(self._calls)
        self._logger.info("tool-call summary | %s", summarize_tool_calls(self._last_run))
        if event.result is not None:
            usage = event.result.metrics.accumulated_usage
            self._logger.info(
                "run metrics | %s",
                summarize_usage(
                    input_tokens=usage["inputTokens"],
                    output_tokens=usage["outputTokens"],
                    total_tokens=usage["totalTokens"],
                    model_latency_ms=event.result.metrics.accumulated_metrics["latencyMs"],
                ),
            )
        self._starts.clear()
        self._calls.clear()
